use_frameworks!

platform :ios, '10.0'

target 'gWebRTCLib_Example' do
  pod 'gWebRTCLib', :path => '../'

  target 'gWebRTCLib_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
